using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TownGameBot.Models
{
    public class CityList
    {
        public CityModel[] CityModels { get; set; }
//                                                    = new CityModel[] {   
//                                                                                               new CityModel { City = "Майкоп"},
//                                                                                                new CityModel { City = "Уфа"},
//                                                                                              new CityModel { City = "Горно-Алтайск"},
//                                                                                                new CityModel { City = "Махачкала"},
//                                                                                                new CityModel { City = "Нальчик"},
//                                                                                                new CityModel { City = "Элиста"},
//                                                                                                new CityModel { City = "Черкесск"},
//                                                                                                new CityModel { City = "Петрозаводск"},
//                                                                                                new CityModel { City = "Сыктывкар"},
//                                                                                                new CityModel { City = "Йошкар-Ола"},
//                                                                                                new CityModel { City = "Саранск"},
//                                                                                                new CityModel { City = "Якутск"},
//                                                                                                new CityModel { City = "Владикавказ"},
//                                                                                                new CityModel { City = "Кызыл"},
//                                                                                                new CityModel { City = "Ижевск"},
//                                                                                                new CityModel { City = "Абакан"},
//                                                                                                new CityModel { City = "Барнаул"},
//                                                                                                new CityModel { City = "Краснодар"},
//                                                                                                new CityModel { City = "Красноярск"},
//                                                                                                new CityModel { City = "Владивосток"},
//                                                                                                new CityModel { City = "Ставрополь"},
//                                                                                                new CityModel { City = "Хабаровск"},
//                                                                                                new CityModel { City = "Благовещенск"},
//                                                                                                new CityModel { City = "Архангельск"},
//                                                                                                new CityModel { City = "Белгород"},
//                                                                                                new CityModel { City = "Брянск"},
//                                                                                                new CityModel { City = "Владимир"},
//                                                                                                new CityModel { City = "Волгоград"},
//                                                                                                new CityModel { City = "Вологда"},
//                                                                                                new CityModel { City = "Иваново"},
//                                                                                                new CityModel { City = "Иркутск"},
//                                                                                                new CityModel { City = "Калининград"},
//                                                                                                new CityModel { City = "Калуга"},
//                                                                                                new CityModel { City = "Петропавловск-Камчатский"},
//                                                                                                new CityModel { City = "Кемерово"},
//                                                                                                new CityModel { City = "Киров"},
//                                                                                                new CityModel { City = "Кострома"},
//                                                                                                new CityModel { City = "Курган"},
//                                                                                                new CityModel { City = "Курск"},
//                                                                                                new CityModel { City = "Санкт-Петербург"},
//                                                                                                new CityModel { City = "Липецк"},
//                                                                                                new CityModel { City = "Магадан"},
//                                                                                                new CityModel { City = "Москва", NamedCity = true},
//                                                                                                new CityModel { City = "Мурманск"},
//                                                                                                new CityModel { City = "Нижний Новгород"},
//                                                                                                new CityModel { City = "Новгород"},
//                                                                                                new CityModel { City = "Новосибирск"},
//                                                                                                new CityModel { City = "Омск"},
//                                                                                                new CityModel { City = "Оренбург"},
//                                                                                                new CityModel { City = "Орел"},
//                                                                                                new CityModel { City = "Пенза"},
//                                                                                                new CityModel { City = "Псков"},
//                                                                                                new CityModel { City = "Ростов-на-Дону"},
//                                                                                                new CityModel { City = "Самара"},
//                                                                                                new CityModel { City = "Саратов"},
//                                                                                                new CityModel { City = "Южно-Сахалинск"},
//                                                                                                new CityModel { City = "Екатеринбург"},
//                                                                                                new CityModel { City = "Смоленск"},
//                                                                                                new CityModel { City = "Тамбов"},
//                                                                                                new CityModel { City = "Томск"},
//                                                                                                new CityModel { City = "Тула"},
//                                                                                                new CityModel { City = "Ульяновск"},
//                                                                                                new CityModel { City = "Челябинск"},
//                                                                                                new CityModel { City = "Чита"},
//                                                                                                new CityModel { City = "Биробиджан"},
//                                                                                                new CityModel { City = "Агинское"},
//                                                                                                new CityModel { City = "Кудымкар"},
//                                                                                                new CityModel { City = "Палана"},
//                                                                                                new CityModel { City = "Нарьян-Мар"},
//                                                                                                new CityModel { City = "Астрахань"},
//                                                                                                new CityModel { City = "Дудинка"},
//                                                                                                new CityModel { City = "Усть-Ордынский"},
//                                                                                                new CityModel { City = "Ханты-Мансийск"},
//                                                                                                new CityModel { City = "Тура"},
//                                                                                                new CityModel { City = "Салехард"},
//                                                                                                new CityModel { City = "Грозный"}
//                                                                      };
    }
}
